pool:
  vmImage: 'windows-2019'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    packageType: runtime

- task: UseDotNet@2
  inputs:
    version: '3.0.x'
    packageType: runtime

- task: DotNetCoreCLI@2
  displayName: 'DotNet Restore'
  inputs:
    command: restore
    projects: '$(Parameters.solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'
  displayName: 'dotnet build $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'

- task: CopyFiles@2
  displayName: 'Preparing NuGet packages'
  inputs:
    Contents: '**\AlbanianXrm.PowerPlatform.EntitySerializer*.nupkg'
    TargetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  